services:
  client:
    container_name: client
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:8080
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: rebuild
          path: ./frontend
  service:
    image: ghcr.io/wms-dev/hacknation/prawda-w-sieci
    container_name: backend
    restart: unless-stopped
    build:
      context: ./backend/hacknation
      dockerfile: Dockerfile
    environment:
      - SERVICE_DB_URL=jdbc:postgresql://postgresdb:5432/hacknation
      - SERVICE_DB_LOGIN=postgres
      - SERVICE_DB_PASSWORD=postgres
    ports:
      - "8080:8080"
    depends_on:
      postgresdb:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./backend/hacknation/src

  postgresdb:
    image: postgres:16
    container_name: postgresdb
    environment:
      POSTGRES_USER: ${SERVICE_DB_LOGIN}
      POSTGRES_PASSWORD: ${SERVICE_DB_PASSWORD}
      POSTGRES_DB: ${SERVICE_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres --dbname=${SERVICE_DB_NAME}
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  default:
    name: hacknation-network
    external: true
