services:
  #  client:
  #    container_name: client
  #    restart: always
  #    build:
  #      context: ./frontend
  #      dockerfile: Dockerfile
  #    ports:
  #      - "3000:3000"
  #    develop:
  #      watch:
  #        - action: rebuild
  #          path: ./frontend

  service:
    container_name: backend
    restart: unless-stopped
    build:
      context: ./backend/hacknation
      dockerfile: Dockerfile
    environment:
      - SERVICE_DB_URL=${SERVICE_DB_URL}
      - SERVICE_DB_LOGIN=${SERVICE_DB_LOGIN}
      - SERVICE_DB_PASSWORD=${SERVICE_DB_PASSWORD}
    ports:
      - "${SERVICE_PORT}:8080"
    depends_on:
      postgresdb:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./backend/hacknation/src

  postgresdb:
    image: postgres:16
    container_name: postgresdb
    environment:
      POSTGRES_USER: ${SERVICE_DB_LOGIN}
      POSTGRES_PASSWORD: ${SERVICE_DB_PASSWORD}
      POSTGRES_DB: ${SERVICE_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres --dbname=${SERVICE_DB_NAME}
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  default:
    name: hacknation-network
    external: true
